#!/bin/bash

if ! [ -t 0 ]; then
        read -a ref
fi


IFS='/' read -ra REF <<< "${ref[2]}"
branch="${REF[2]}"

if [ $branch == "main" ]; then
        crumb=$(curl -u "jenkins:$(echo "amVua2lucwo="|base64 -d)" -s 'http://jenkins:8080/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)')
        curl -u "jenkins:$(echo "amVua2lucwo="|base64 -d)" -H "$crumb" -X POST http://jenkins:8080/job/pipeline-docker-maven/build?delay=0sec

        if [ $? -eq 0 ]; then
                echo "*** Ok"
        else
                echo "*** Error"
        fi

fi
