pipeline {

    agent any
    
    stages {

        stage('Build') {
            steps {
                sh '''
                  echo Building
                '''
            }
        }

        stage('Test') {
            steps {
                sh 'echo Test'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                  echo Deploying
                   '''
            }
        }
    }
}
